// <auto-generated />
using Labb3_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb3_API.Migrations
{
    [DbContext(typeof(InterestsDbContext))]
    partial class InterestsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb3_API.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Capturing landscapes and portraits.",
                            PersonId = 1,
                            Title = "Photography"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Exploring trails and nature.",
                            PersonId = 1,
                            Title = "Hiking"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Building indie games with Unity.",
                            PersonId = 2,
                            Title = "Game Dev"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Contributing to OSS projects.",
                            PersonId = 2,
                            Title = "Open Source"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bread, pastries, and sourdough.",
                            PersonId = 3,
                            Title = "Baking"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            PersonId = 1,
                            Url = "https://www.flickr.com"
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 1,
                            PersonId = 1,
                            Url = "https://www.500px.com"
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 2,
                            PersonId = 1,
                            Url = "https://www.alltrails.com"
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 3,
                            PersonId = 2,
                            Url = "https://www.unity.com"
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 3,
                            PersonId = 2,
                            Url = "https://itch.io"
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 4,
                            PersonId = 2,
                            Url = "https://github.com"
                        },
                        new
                        {
                            Id = 7,
                            InterestId = 5,
                            PersonId = 3,
                            Url = "https://www.kingarthurbaking.com"
                        },
                        new
                        {
                            Id = 8,
                            InterestId = 5,
                            PersonId = 3,
                            Url = "https://www.theperfectloaf.com"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            Name = "Alice Svensson",
                            Phone = "+46701234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            Name = "Bob Karlsson",
                            Phone = "+46709876543"
                        },
                        new
                        {
                            Id = 3,
                            Email = "clara@example.com",
                            Name = "Clara Nilsson",
                            Phone = "+46701112233"
                        });
                });

            modelBuilder.Entity("Labb3_API.Models.Interest", b =>
                {
                    b.HasOne("Labb3_API.Models.Person", "Person")
                        .WithMany("Interests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb3_API.Models.Link", b =>
                {
                    b.HasOne("Labb3_API.Models.Interest", "Interest")
                        .WithMany("Links")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb3_API.Models.Person", "Person")
                        .WithMany("Links")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb3_API.Models.Interest", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Labb3_API.Models.Person", b =>
                {
                    b.Navigation("Interests");

                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
